package vista;

import java.awt.Color;

/**
 * @author Dizan
 */
public class vistaCiclosEscolares extends javax.swing.JDialog {

    boolean esBisiestoInicio = false; 
    boolean cambioAñoInicio = false;
    boolean esBisiestoFin = false; 
    boolean cambioAñoFin = false;
    /**
     * Creates new form vistaReinscripcion
     */
    public vistaCiclosEscolares(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void mes31Inicio() {
        boxDiaInicio.removeAllItems();
        boxDiaInicio.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaInicio.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaInicio.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 30; k++) {
            boxDiaInicio.addItem(String.valueOf(k));
        }
        for (int f = 30; f < 32; f++) {
            boxDiaInicio.addItem(String.valueOf(f));
        }
    }

    public void mes30Inicio() {
        boxDiaInicio.removeAllItems();
        boxDiaInicio.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaInicio.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaInicio.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 30; k++) {
            boxDiaInicio.addItem(String.valueOf(k));
        }
        for (int f = 30; f < 31; f++) {
            boxDiaInicio.addItem(String.valueOf(f));
        }
    }

    public void mes28Inicio() {
        boxDiaInicio.removeAllItems();
        boxDiaInicio.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaInicio.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaInicio.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 29; k++) {
            boxDiaInicio.addItem(String.valueOf(k));
        }
    }

    public void mes29Inicio() {
        boxDiaInicio.removeAllItems();
        boxDiaInicio.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaInicio.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaInicio.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 30; k++) {
            boxDiaInicio.addItem(String.valueOf(k));
        }
    }
    
    public void mes31Fin() {
        boxDiaFin.removeAllItems();
        boxDiaFin.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaFin.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaFin.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 30; k++) {
            boxDiaFin.addItem(String.valueOf(k));
        }
        for (int f = 30; f < 32; f++) {
            boxDiaFin.addItem(String.valueOf(f));
        }
    }

    public void mes30Fin() {
        boxDiaFin.removeAllItems();
        boxDiaFin.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaFin.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaFin.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 30; k++) {
           boxDiaFin.addItem(String.valueOf(k));
        }
        for (int f = 30; f < 31; f++) {
            boxDiaFin.addItem(String.valueOf(f));
        }
    }

    public void mes28Fin() {
        boxDiaFin.removeAllItems();
        boxDiaFin.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaFin.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaFin.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 29; k++) {
            boxDiaFin.addItem(String.valueOf(k));
        }
    }

    public void mes29Fin() {
        boxDiaFin.removeAllItems();
        boxDiaFin.addItem("Dia");
        for (int i = 1; i < 10; i++) {
            boxDiaFin.addItem("0" + i);
        }
        for (int j = 10; j < 20; j++) {
            boxDiaFin.addItem(String.valueOf(j));

        }
        for (int k = 20; k < 30; k++) {
            boxDiaFin.addItem(String.valueOf(k));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        labelCicloEscolar = new javax.swing.JLabel();
        labelInicio = new javax.swing.JLabel();
        fieldCicloEscolar = new javax.swing.JTextField();
        labelFin = new javax.swing.JLabel();
        boxAñoInicio = new javax.swing.JComboBox<>();
        boxMesInicio = new javax.swing.JComboBox<>();
        boxDiaInicio = new javax.swing.JComboBox<>();
        boxAñoFin = new javax.swing.JComboBox<>();
        boxMesFin = new javax.swing.JComboBox<>();
        boxDiaFin = new javax.swing.JComboBox<>();
        panelBotones = new javax.swing.JPanel();
        botonCrear = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 300));
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelPrincipal.setBackground(new java.awt.Color(8, 38, 67));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        panelTitulo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panelTitulo.setLayout(new java.awt.GridBagLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Crear ciclo escolar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelTitulo.add(labelTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelOpciones.setBackground(new java.awt.Color(8, 38, 67));
        panelOpciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOpciones.setLayout(new java.awt.GridBagLayout());

        labelCicloEscolar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCicloEscolar.setForeground(new java.awt.Color(255, 255, 255));
        labelCicloEscolar.setText("Ciclo escolar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelOpciones.add(labelCicloEscolar, gridBagConstraints);

        labelInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelInicio.setForeground(new java.awt.Color(255, 255, 255));
        labelInicio.setText("Inicio insc/reinsc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelOpciones.add(labelInicio, gridBagConstraints);

        fieldCicloEscolar.setText("XXXX-XXXX");
        fieldCicloEscolar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCicloEscolarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCicloEscolarFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelOpciones.add(fieldCicloEscolar, gridBagConstraints);

        labelFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFin.setForeground(new java.awt.Color(255, 255, 255));
        labelFin.setText("Fin insc/reinsc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelOpciones.add(labelFin, gridBagConstraints);

        boxAñoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        boxAñoInicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxAñoInicioItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        panelOpciones.add(boxAñoInicio, gridBagConstraints);

        boxMesInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        boxMesInicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxMesInicioItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        panelOpciones.add(boxMesInicio, gridBagConstraints);

        boxDiaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panelOpciones.add(boxDiaInicio, gridBagConstraints);

        boxAñoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        boxAñoFin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxAñoFinItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        panelOpciones.add(boxAñoFin, gridBagConstraints);

        boxMesFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        boxMesFin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxMesFinItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        panelOpciones.add(boxMesFin, gridBagConstraints);

        boxDiaFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        panelOpciones.add(boxDiaFin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelPrincipal.add(panelOpciones, gridBagConstraints);

        panelBotones.setBackground(new java.awt.Color(8, 38, 67));
        panelBotones.setLayout(new java.awt.GridBagLayout());

        botonCrear.setBackground(new java.awt.Color(8, 38, 67));
        botonCrear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(255, 255, 255));
        botonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder_add32x32.png"))); // NOI18N
        botonCrear.setText("Crear");
        botonCrear.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelBotones.add(botonCrear, gridBagConstraints);

        botonActualizar.setBackground(new java.awt.Color(8, 38, 67));
        botonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelBotones.add(botonActualizar, gridBagConstraints);

        botonEliminar.setBackground(new java.awt.Color(8, 38, 67));
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder_remove32x32.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelBotones.add(botonEliminar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        panelPrincipal.add(panelBotones, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxAñoInicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxAñoInicioItemStateChanged
        // TODO add your handling code here:
        cambioAñoInicio = true;
        String añobisiesto = (String) boxAñoInicio.getSelectedItem();
        if (!añobisiesto.equals("Año")) {
            if ((añobisiesto.equals("2000"))
                    || (añobisiesto.equals("2004"))
                    || (añobisiesto.equals("2008"))
                    || (añobisiesto.equals("2012"))
                    || (añobisiesto.equals("2016"))
                    || (añobisiesto.equals("2020"))
                    || (añobisiesto.equals("2024"))
                    || (añobisiesto.equals("2028"))
                    || (añobisiesto.equals("2032"))) {
                esBisiestoInicio = true;
                boxMesInicioItemStateChanged(evt);
            } else {
                esBisiestoInicio = false;
                boxMesInicioItemStateChanged(evt);
            }
        }
        else
            cambioAñoInicio = false;
    }//GEN-LAST:event_boxAñoInicioItemStateChanged

    private void boxMesInicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxMesInicioItemStateChanged
        // TODO add your handling code here:
        String seleccion = (String) boxMesInicio.getSelectedItem();
        if (seleccion.equals("01") || seleccion.equals("03") || seleccion.equals("05") || seleccion.equals("07") ||seleccion.equals("8") || seleccion.equals("10") || seleccion.equals("12"))  {
             mes31Inicio();
            //Abril, Junio, Septiembre y Noviembre.
        }
        if (seleccion.equals("04") || seleccion.equals("06") || seleccion.equals("09") || seleccion.equals("11")) {
            mes30Inicio();
        }
        if (seleccion.equals("02") && esBisiestoInicio) {
            mes29Inicio();
        }
        if (seleccion.equals("02") && esBisiestoInicio == false) {
            mes28Inicio();
        }
    }//GEN-LAST:event_boxMesInicioItemStateChanged

    private void boxAñoFinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxAñoFinItemStateChanged
        // TODO add your handling code here:
        cambioAñoFin = true;
        String añobisiesto = (String) boxAñoFin.getSelectedItem();
        if (!añobisiesto.equals("Año")) {
            if ((añobisiesto.equals("2000"))
                    || (añobisiesto.equals("2004"))
                    || (añobisiesto.equals("2008"))
                    || (añobisiesto.equals("2012"))
                    || (añobisiesto.equals("2016"))
                    || (añobisiesto.equals("2020"))
                    || (añobisiesto.equals("2024"))
                    || (añobisiesto.equals("2028"))
                    || (añobisiesto.equals("2032"))) {
                esBisiestoFin = true;
                boxMesFinItemStateChanged(evt);
            } else {
                esBisiestoFin = false;
                boxMesFinItemStateChanged(evt);
            }
        }
        else
            cambioAñoFin = false;
    }//GEN-LAST:event_boxAñoFinItemStateChanged

    private void boxMesFinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxMesFinItemStateChanged
        // TODO add your handling code here:
        String seleccion = (String) boxMesFin.getSelectedItem();
        if (seleccion.equals("01") || seleccion.equals("03") || seleccion.equals("05") || seleccion.equals("07") ||seleccion.equals("8") || seleccion.equals("10") || seleccion.equals("12"))  {
             mes31Fin();
            //Abril, Junio, Septiembre y Noviembre.
        }
        if (seleccion.equals("04") || seleccion.equals("06") || seleccion.equals("09") || seleccion.equals("11")) {
            mes30Fin();
        }
        if (seleccion.equals("02") && esBisiestoFin) {
            mes29Fin();
        }
        if (seleccion.equals("02") && esBisiestoFin == false) {
            mes28Fin();
        }
    }//GEN-LAST:event_boxMesFinItemStateChanged

    private void fieldCicloEscolarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCicloEscolarFocusGained
        // TODO add your handling code here:
         if ("XXXX-XXXX".equals(fieldCicloEscolar.getText())) {
                fieldCicloEscolar.setText("");
                fieldCicloEscolar.setForeground(Color.BLACK);  
            }
    }//GEN-LAST:event_fieldCicloEscolarFocusGained

    private void fieldCicloEscolarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCicloEscolarFocusLost
        // TODO add your handling code here:
        if (fieldCicloEscolar.getText().isEmpty()) {
            fieldCicloEscolar.setText("XXXX-XXXX");
            fieldCicloEscolar.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldCicloEscolarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCiclosEscolares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCiclosEscolares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCiclosEscolares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCiclosEscolares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaCiclosEscolares dialog = new vistaCiclosEscolares(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonActualizar;
    public javax.swing.JButton botonCrear;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JComboBox<String> boxAñoFin;
    public javax.swing.JComboBox<String> boxAñoInicio;
    public javax.swing.JComboBox<String> boxDiaFin;
    public javax.swing.JComboBox<String> boxDiaInicio;
    public javax.swing.JComboBox<String> boxMesFin;
    public javax.swing.JComboBox<String> boxMesInicio;
    public javax.swing.JTextField fieldCicloEscolar;
    private javax.swing.JLabel labelCicloEscolar;
    private javax.swing.JLabel labelFin;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
