/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Dizan
 */
public class vistaAvances extends javax.swing.JDialog {

    /**
     * Creates new form vistaAvances
     */
    public vistaAvances(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoEtapasT1 = new javax.swing.ButtonGroup();
        grupoEtapasT2 = new javax.swing.ButtonGroup();
        grupoEtapasT3 = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelBusqueda = new javax.swing.JPanel();
        fieldApe_paterno = new javax.swing.JTextField();
        fieldApe_materno = new javax.swing.JTextField();
        fieldNombre = new javax.swing.JTextField();
        fieldNumeroControl = new javax.swing.JTextField();
        boxCicloEscolar = new javax.swing.JComboBox<>();
        boxGrado = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();
        panelAvances = new javax.swing.JPanel();
        labelTituloT1 = new javax.swing.JLabel();
        checkEtapa1T1 = new javax.swing.JCheckBox();
        checkEtapa2T1 = new javax.swing.JCheckBox();
        checkEtapa3T1 = new javax.swing.JCheckBox();
        checkEtapa4T1 = new javax.swing.JCheckBox();
        checkEtapa5T1 = new javax.swing.JCheckBox();
        checkEtapa6T1 = new javax.swing.JCheckBox();
        checkEtapa7T1 = new javax.swing.JCheckBox();
        labelTituloT2 = new javax.swing.JLabel();
        checkEtapa1T2 = new javax.swing.JCheckBox();
        checkEtapa2T2 = new javax.swing.JCheckBox();
        checkEtapa3T2 = new javax.swing.JCheckBox();
        checkEtapa4T2 = new javax.swing.JCheckBox();
        checkEtapa5T2 = new javax.swing.JCheckBox();
        checkEtapa6T2 = new javax.swing.JCheckBox();
        checkEtapa7T2 = new javax.swing.JCheckBox();
        labelTituloT3 = new javax.swing.JLabel();
        checkEtapa1T3 = new javax.swing.JCheckBox();
        checkEtapa2T3 = new javax.swing.JCheckBox();
        checkEtapa3T3 = new javax.swing.JCheckBox();
        checkEtapa4T3 = new javax.swing.JCheckBox();
        checkEtapa5T3 = new javax.swing.JCheckBox();
        checkEtapa6T3 = new javax.swing.JCheckBox();
        checkEtapa7T3 = new javax.swing.JCheckBox();
        labelTituloEtapas = new javax.swing.JLabel();
        textEtapa1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textEtapa2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        textEtapa3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        textEtapa4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        textEtapa5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        textEtapa6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        textEtapa7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        panelBotones = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelPrincipal.setBackground(new java.awt.Color(8, 38, 67));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        panelTitulo.setLayout(new java.awt.GridLayout(1, 0));

        labelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Registro de avances");
        panelTitulo.add(labelTitulo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelBusqueda.setBackground(new java.awt.Color(8, 38, 67));
        panelBusqueda.setLayout(new java.awt.GridBagLayout());

        fieldApe_paterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldApe_paterno.setText("Apellido paterno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        panelBusqueda.add(fieldApe_paterno, gridBagConstraints);

        fieldApe_materno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldApe_materno.setText("Apellido materno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(fieldApe_materno, gridBagConstraints);

        fieldNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        panelBusqueda.add(fieldNombre, gridBagConstraints);

        fieldNumeroControl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldNumeroControl.setText("Numero de control");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(fieldNumeroControl, gridBagConstraints);

        boxCicloEscolar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxCicloEscolar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciclo escolar" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(boxCicloEscolar, gridBagConstraints);

        boxGrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grado" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(boxGrado, gridBagConstraints);

        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBuscar.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        panelBusqueda.add(botonBuscar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelBusqueda, gridBagConstraints);

        panelAvances.setBackground(new java.awt.Color(0, 122, 145));
        panelAvances.setLayout(new java.awt.GridBagLayout());

        labelTituloT1.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloT1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelTituloT1.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloT1.setText("T1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelAvances.add(labelTituloT1, gridBagConstraints);

        checkEtapa1T1.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT1.add(checkEtapa1T1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa1T1, gridBagConstraints);

        checkEtapa2T1.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT1.add(checkEtapa2T1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa2T1, gridBagConstraints);

        checkEtapa3T1.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT1.add(checkEtapa3T1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa3T1, gridBagConstraints);

        checkEtapa4T1.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT1.add(checkEtapa4T1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa4T1, gridBagConstraints);

        checkEtapa5T1.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT1.add(checkEtapa5T1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa5T1, gridBagConstraints);

        checkEtapa6T1.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT1.add(checkEtapa6T1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa6T1, gridBagConstraints);

        checkEtapa7T1.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT1.add(checkEtapa7T1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa7T1, gridBagConstraints);

        labelTituloT2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelTituloT2.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloT2.setText("T2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelAvances.add(labelTituloT2, gridBagConstraints);

        checkEtapa1T2.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT2.add(checkEtapa1T2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa1T2, gridBagConstraints);

        checkEtapa2T2.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT2.add(checkEtapa2T2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa2T2, gridBagConstraints);

        checkEtapa3T2.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT2.add(checkEtapa3T2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa3T2, gridBagConstraints);

        checkEtapa4T2.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT2.add(checkEtapa4T2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa4T2, gridBagConstraints);

        checkEtapa5T2.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT2.add(checkEtapa5T2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa5T2, gridBagConstraints);

        checkEtapa6T2.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT2.add(checkEtapa6T2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa6T2, gridBagConstraints);

        checkEtapa7T2.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT2.add(checkEtapa7T2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa7T2, gridBagConstraints);

        labelTituloT3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelTituloT3.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloT3.setText("T3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelAvances.add(labelTituloT3, gridBagConstraints);

        checkEtapa1T3.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT3.add(checkEtapa1T3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa1T3, gridBagConstraints);

        checkEtapa2T3.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT3.add(checkEtapa2T3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa2T3, gridBagConstraints);

        checkEtapa3T3.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT3.add(checkEtapa3T3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa3T3, gridBagConstraints);

        checkEtapa4T3.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT3.add(checkEtapa4T3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa4T3, gridBagConstraints);

        checkEtapa5T3.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT3.add(checkEtapa5T3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa5T3, gridBagConstraints);

        checkEtapa6T3.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapasT3.add(checkEtapa6T3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa6T3, gridBagConstraints);

        checkEtapa7T3.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapasT3.add(checkEtapa7T3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa7T3, gridBagConstraints);

        labelTituloEtapas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelTituloEtapas.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloEtapas.setText("Etapas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelAvances.add(labelTituloEtapas, gridBagConstraints);

        textEtapa1.setBorder(null);
        textEtapa1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textEtapa1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 87, 126));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 204, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Hace trazos que no son letras. Usa algunas letras que conoce, hace garabatos.");
        jTextArea1.setBorder(null);
        textEtapa1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(textEtapa1, gridBagConstraints);

        textEtapa2.setBorder(null);
        textEtapa2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textEtapa2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 122, 145));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Llena la mitad del renglón o todo el renglón de la hoja con muchas letras que conoce.");
        textEtapa2.setViewportView(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(textEtapa2, gridBagConstraints);

        textEtapa3.setBackground(new java.awt.Color(0, 87, 126));
        textEtapa3.setBorder(null);
        textEtapa3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textEtapa3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(0, 87, 126));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(153, 204, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Siempre usa la misma cantidad de letras y las mismas letras (dos, tres, cuatro) para escribir palabras distintas.");
        textEtapa3.setViewportView(jTextArea3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(textEtapa3, gridBagConstraints);

        textEtapa4.setBorder(null);
        textEtapa4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textEtapa4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(0, 122, 145));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Cambia la cantidad de letras y escribe letras distintas para cada palabra.");
        textEtapa4.setViewportView(jTextArea4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(textEtapa4, gridBagConstraints);

        textEtapa5.setBorder(null);
        textEtapa5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textEtapa5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(0, 87, 126));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(153, 204, 255));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Usa una letra para cada silaba de la palabra que quiere escribir y esta no corresponde, por ejemplo al escribir pato, el niño escribe HD, es decir, dos silabas, dos letras.");
        textEtapa5.setViewportView(jTextArea5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(textEtapa5, gridBagConstraints);

        textEtapa6.setBorder(null);
        textEtapa6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textEtapa6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(0, 122, 145));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText("Ya lo hace con letras que corresponden a la palabra que quiere escribir por ejemplo, cuando escribe gato, escribe \"GAO\".");
        textEtapa6.setViewportView(jTextArea6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(textEtapa6, gridBagConstraints);

        textEtapa7.setBorder(null);
        textEtapa7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textEtapa7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(0, 87, 126));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(153, 204, 255));
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setText("Ya lo hace convencionalmente, es decir, ya sabe escribir aunque en ocasiones tiene dificultades con letras como J,C,S,V o B.");
        textEtapa7.setViewportView(jTextArea7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(textEtapa7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelAvances, gridBagConstraints);

        panelBotones.setBackground(new java.awt.Color(8, 38, 67));
        panelBotones.setLayout(new java.awt.GridBagLayout());

        botonGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonGuardar.setText("Guardar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        panelBotones.add(botonGuardar, gridBagConstraints);

        botonActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonActualizar.setText("Actualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        panelBotones.add(botonActualizar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelPrincipal.add(panelBotones, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaAvances dialog = new vistaAvances(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox<String> boxCicloEscolar;
    private javax.swing.JComboBox<String> boxGrado;
    private javax.swing.JCheckBox checkEtapa1T1;
    private javax.swing.JCheckBox checkEtapa1T2;
    private javax.swing.JCheckBox checkEtapa1T3;
    private javax.swing.JCheckBox checkEtapa2T1;
    private javax.swing.JCheckBox checkEtapa2T2;
    private javax.swing.JCheckBox checkEtapa2T3;
    private javax.swing.JCheckBox checkEtapa3T1;
    private javax.swing.JCheckBox checkEtapa3T2;
    private javax.swing.JCheckBox checkEtapa3T3;
    private javax.swing.JCheckBox checkEtapa4T1;
    private javax.swing.JCheckBox checkEtapa4T2;
    private javax.swing.JCheckBox checkEtapa4T3;
    private javax.swing.JCheckBox checkEtapa5T1;
    private javax.swing.JCheckBox checkEtapa5T2;
    private javax.swing.JCheckBox checkEtapa5T3;
    private javax.swing.JCheckBox checkEtapa6T1;
    private javax.swing.JCheckBox checkEtapa6T2;
    private javax.swing.JCheckBox checkEtapa6T3;
    private javax.swing.JCheckBox checkEtapa7T1;
    private javax.swing.JCheckBox checkEtapa7T2;
    private javax.swing.JCheckBox checkEtapa7T3;
    private javax.swing.JTextField fieldApe_materno;
    private javax.swing.JTextField fieldApe_paterno;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNumeroControl;
    private javax.swing.ButtonGroup grupoEtapasT1;
    private javax.swing.ButtonGroup grupoEtapasT2;
    private javax.swing.ButtonGroup grupoEtapasT3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloEtapas;
    private javax.swing.JLabel labelTituloT1;
    private javax.swing.JLabel labelTituloT2;
    private javax.swing.JLabel labelTituloT3;
    private javax.swing.JPanel panelAvances;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane textEtapa1;
    private javax.swing.JScrollPane textEtapa2;
    private javax.swing.JScrollPane textEtapa3;
    private javax.swing.JScrollPane textEtapa4;
    private javax.swing.JScrollPane textEtapa5;
    private javax.swing.JScrollPane textEtapa6;
    private javax.swing.JScrollPane textEtapa7;
    // End of variables declaration//GEN-END:variables
}
