/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author Dizan
 */
public class vistaAvances extends javax.swing.JDialog {

    /**
     * Creates new form vistaAvances
     */
    public vistaAvances(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        botonGrupo();
    }
    
    private void botonGrupo(){
        checkEtapa1.setActionCommand("Etapa 1");
        checkEtapa2.setActionCommand("Etapa 2");
        checkEtapa3.setActionCommand("Etapa 3");
        checkEtapa4.setActionCommand("Etapa 4");
        checkEtapa5.setActionCommand("Etapa 5");
        checkEtapa6.setActionCommand("Etapa 6");
        checkEtapa7.setActionCommand("Etapa 7");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoEtapas = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelBusqueda = new javax.swing.JPanel();
        fieldApe_paterno = new javax.swing.JTextField();
        fieldApe_materno = new javax.swing.JTextField();
        fieldNombre = new javax.swing.JTextField();
        fieldNumeroControl = new javax.swing.JTextField();
        boxCicloEscolar = new javax.swing.JComboBox<>();
        boxGrado = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();
        boxTrimestre = new javax.swing.JComboBox<>();
        panelAvances = new javax.swing.JPanel();
        labelTituloT1 = new javax.swing.JLabel();
        checkEtapa1 = new javax.swing.JCheckBox();
        checkEtapa2 = new javax.swing.JCheckBox();
        checkEtapa3 = new javax.swing.JCheckBox();
        checkEtapa4 = new javax.swing.JCheckBox();
        checkEtapa5 = new javax.swing.JCheckBox();
        checkEtapa6 = new javax.swing.JCheckBox();
        checkEtapa7 = new javax.swing.JCheckBox();
        labelTituloEtapas = new javax.swing.JLabel();
        stextEtapa1 = new javax.swing.JScrollPane();
        textEtapa1 = new javax.swing.JTextPane();
        stextEtapa2 = new javax.swing.JScrollPane();
        textEtapa2 = new javax.swing.JTextPane();
        stextEtapa3 = new javax.swing.JScrollPane();
        textEtapa3 = new javax.swing.JTextPane();
        stextEtapa4 = new javax.swing.JScrollPane();
        textEtapa4 = new javax.swing.JTextPane();
        stextEtapa5 = new javax.swing.JScrollPane();
        textEtapa5 = new javax.swing.JTextPane();
        stextEtapa6 = new javax.swing.JScrollPane();
        textEtapa6 = new javax.swing.JTextPane();
        stextEtapa7 = new javax.swing.JScrollPane();
        textEtapa7 = new javax.swing.JTextPane();
        panelBotones = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 580));
        setPreferredSize(new java.awt.Dimension(800, 580));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelPrincipal.setBackground(new java.awt.Color(8, 38, 67));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        panelTitulo.setLayout(new java.awt.GridLayout(1, 0));

        labelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Registro de avances");
        panelTitulo.add(labelTitulo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelBusqueda.setBackground(new java.awt.Color(8, 38, 67));
        panelBusqueda.setLayout(new java.awt.GridBagLayout());

        fieldApe_paterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldApe_paterno.setForeground(new java.awt.Color(153, 153, 153));
        fieldApe_paterno.setText("Apellido Paterno");
        fieldApe_paterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldApe_paternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldApe_paternoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        panelBusqueda.add(fieldApe_paterno, gridBagConstraints);

        fieldApe_materno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldApe_materno.setForeground(new java.awt.Color(153, 153, 153));
        fieldApe_materno.setText("Apellido Materno");
        fieldApe_materno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldApe_maternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldApe_maternoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(fieldApe_materno, gridBagConstraints);

        fieldNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldNombre.setForeground(new java.awt.Color(153, 153, 153));
        fieldNombre.setText("Nombre");
        fieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNombreFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        panelBusqueda.add(fieldNombre, gridBagConstraints);

        fieldNumeroControl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldNumeroControl.setForeground(new java.awt.Color(153, 153, 153));
        fieldNumeroControl.setText("Numero de control");
        fieldNumeroControl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNumeroControlFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNumeroControlFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(fieldNumeroControl, gridBagConstraints);

        boxCicloEscolar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxCicloEscolar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciclo escolar" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(boxCicloEscolar, gridBagConstraints);

        boxGrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grado", "1", "2", "3", "4", "5", "6" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBusqueda.add(boxGrado, gridBagConstraints);

        botonBuscar.setBackground(new java.awt.Color(8, 38, 67));
        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.setBorder(null);
        botonBuscar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelBusqueda.add(botonBuscar, gridBagConstraints);

        boxTrimestre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxTrimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trimestre", "1", "2", "3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        panelBusqueda.add(boxTrimestre, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelBusqueda, gridBagConstraints);

        panelAvances.setBackground(new java.awt.Color(0, 122, 145));
        panelAvances.setLayout(new java.awt.GridBagLayout());

        labelTituloT1.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloT1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelTituloT1.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloT1.setText("Trimestre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelAvances.add(labelTituloT1, gridBagConstraints);

        checkEtapa1.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapas.add(checkEtapa1);
        checkEtapa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkEtapa1.setForeground(new java.awt.Color(153, 204, 255));
        checkEtapa1.setSelected(true);
        checkEtapa1.setText("Etapa 1");
        checkEtapa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkEtapa1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        checkEtapa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEtapa1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa1, gridBagConstraints);

        checkEtapa2.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapas.add(checkEtapa2);
        checkEtapa2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkEtapa2.setText("Etapa 2");
        checkEtapa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa2, gridBagConstraints);

        checkEtapa3.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapas.add(checkEtapa3);
        checkEtapa3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkEtapa3.setForeground(new java.awt.Color(153, 204, 255));
        checkEtapa3.setText("Etapa 3");
        checkEtapa3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa3, gridBagConstraints);

        checkEtapa4.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapas.add(checkEtapa4);
        checkEtapa4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkEtapa4.setText("Etapa 4");
        checkEtapa4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa4, gridBagConstraints);

        checkEtapa5.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapas.add(checkEtapa5);
        checkEtapa5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkEtapa5.setForeground(new java.awt.Color(153, 204, 255));
        checkEtapa5.setText("Etapa 5");
        checkEtapa5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa5, gridBagConstraints);

        checkEtapa6.setBackground(new java.awt.Color(0, 122, 145));
        grupoEtapas.add(checkEtapa6);
        checkEtapa6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkEtapa6.setText("Etapa 6");
        checkEtapa6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa6, gridBagConstraints);

        checkEtapa7.setBackground(new java.awt.Color(0, 87, 126));
        grupoEtapas.add(checkEtapa7);
        checkEtapa7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkEtapa7.setForeground(new java.awt.Color(153, 204, 255));
        checkEtapa7.setText("Etapa 7");
        checkEtapa7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 1.0;
        panelAvances.add(checkEtapa7, gridBagConstraints);

        labelTituloEtapas.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelTituloEtapas.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloEtapas.setText("Etapas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelAvances.add(labelTituloEtapas, gridBagConstraints);

        stextEtapa1.setBorder(null);

        textEtapa1.setBackground(new java.awt.Color(0, 87, 126));
        textEtapa1.setBorder(null);
        textEtapa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEtapa1.setForeground(new java.awt.Color(153, 204, 255));
        textEtapa1.setText("Hace trazos que no son letras. Usa algunas letras que conoce, hace garabatos.");
        textEtapa1.setDisabledTextColor(new java.awt.Color(153, 153, 255));
        textEtapa1.setFocusable(false);
        stextEtapa1.setViewportView(textEtapa1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelAvances.add(stextEtapa1, gridBagConstraints);

        stextEtapa2.setBorder(null);

        textEtapa2.setBackground(new java.awt.Color(0, 122, 145));
        textEtapa2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEtapa2.setText("Llena la mitad del renglón o todo el renglón de la hoja con muchas letras que conoce.");
        stextEtapa2.setViewportView(textEtapa2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelAvances.add(stextEtapa2, gridBagConstraints);

        stextEtapa3.setBorder(null);

        textEtapa3.setBackground(new java.awt.Color(0, 87, 126));
        textEtapa3.setBorder(null);
        textEtapa3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEtapa3.setForeground(new java.awt.Color(153, 204, 255));
        textEtapa3.setText("Siempre usa la misma cantidad de letras y las mismas letras (dos, tres, cuatro) para escribir palabras distintas.");
        textEtapa3.setDisabledTextColor(new java.awt.Color(153, 153, 255));
        textEtapa3.setFocusable(false);
        stextEtapa3.setViewportView(textEtapa3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelAvances.add(stextEtapa3, gridBagConstraints);

        stextEtapa4.setBorder(null);

        textEtapa4.setBackground(new java.awt.Color(0, 122, 145));
        textEtapa4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEtapa4.setText("Cambia la cantidad de letras y escribe letras distintas para cada palabra.");
        stextEtapa4.setViewportView(textEtapa4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelAvances.add(stextEtapa4, gridBagConstraints);

        stextEtapa5.setBorder(null);

        textEtapa5.setBackground(new java.awt.Color(0, 87, 126));
        textEtapa5.setBorder(null);
        textEtapa5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEtapa5.setForeground(new java.awt.Color(153, 204, 255));
        textEtapa5.setText("Usa una letra para cada silaba de la palabra que quiere escribir y esta no corresponde, por ejemplo al escribir pato, el niño escribe HD, es decir, dos silabas, dos letras.");
        textEtapa5.setDisabledTextColor(new java.awt.Color(153, 153, 255));
        textEtapa5.setFocusable(false);
        stextEtapa5.setViewportView(textEtapa5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelAvances.add(stextEtapa5, gridBagConstraints);

        stextEtapa6.setBorder(null);

        textEtapa6.setBackground(new java.awt.Color(0, 122, 145));
        textEtapa6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEtapa6.setText("Ya lo hace con letras que corresponden a la palabra que quiere escribir por ejemplo, cuando escribe gato, escribe \"GAO\".");
        stextEtapa6.setViewportView(textEtapa6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelAvances.add(stextEtapa6, gridBagConstraints);

        stextEtapa7.setBorder(null);

        textEtapa7.setBackground(new java.awt.Color(0, 87, 126));
        textEtapa7.setBorder(null);
        textEtapa7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEtapa7.setForeground(new java.awt.Color(153, 204, 255));
        textEtapa7.setText("Ya lo hace convencionalmente, es decir, ya sabe escribir aunque en ocasiones tiene dificultades con letras como J,C,S,V o B.");
        textEtapa7.setDisabledTextColor(new java.awt.Color(153, 153, 255));
        textEtapa7.setFocusable(false);
        stextEtapa7.setViewportView(textEtapa7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panelAvances.add(stextEtapa7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrincipal.add(panelAvances, gridBagConstraints);

        panelBotones.setBackground(new java.awt.Color(8, 38, 67));
        panelBotones.setLayout(new java.awt.GridBagLayout());

        botonGuardar.setBackground(new java.awt.Color(8, 38, 67));
        botonGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setBorder(null);
        botonGuardar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        panelBotones.add(botonGuardar, gridBagConstraints);

        botonActualizar.setBackground(new java.awt.Color(8, 38, 67));
        botonActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.setBorder(null);
        botonActualizar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        panelBotones.add(botonActualizar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        panelPrincipal.add(panelBotones, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkEtapa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEtapa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEtapa1ActionPerformed

    private void fieldNumeroControlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroControlFocusGained
        // TODO add your handling code here:
        if ("Numero de control".equals(fieldNumeroControl.getText())) {
            fieldNumeroControl.setText("");
            fieldNumeroControl.setForeground(Color.BLACK);   
        }
    }//GEN-LAST:event_fieldNumeroControlFocusGained

    private void fieldNumeroControlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroControlFocusLost
        // TODO add your handling code here:
        if (fieldNumeroControl.getText().isEmpty()) {
            fieldNumeroControl.setText("Numero de control");
             fieldNumeroControl.setForeground(new Color(153, 153,153));
        }
    }//GEN-LAST:event_fieldNumeroControlFocusLost

    private void fieldApe_paternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_paternoFocusGained
        // TODO add your handling code here:
        if ("Apellido Paterno".equals(fieldApe_paterno.getText())) {
                fieldApe_paterno.setText("");
                fieldApe_paterno.setForeground(Color.BLACK); 
        }
    }//GEN-LAST:event_fieldApe_paternoFocusGained

    private void fieldApe_paternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_paternoFocusLost
        // TODO add your handling code here:
        if (fieldApe_paterno.getText().isEmpty()) {
            fieldApe_paterno.setText("Apellido Paterno");
            fieldApe_paterno.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldApe_paternoFocusLost

    private void fieldApe_maternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_maternoFocusGained
        // TODO add your handling code here:
        if ("Apellido Materno".equals(fieldApe_materno.getText())) {
                fieldApe_materno.setText("");
                fieldApe_materno.setForeground(Color.BLACK);  
            } 
    }//GEN-LAST:event_fieldApe_maternoFocusGained

    private void fieldApe_maternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_maternoFocusLost
        // TODO add your handling code here:
         if (fieldApe_materno.getText().isEmpty()) {
            fieldApe_materno.setText("Apellido Materno");
            fieldApe_materno.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldApe_maternoFocusLost

    private void fieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreFocusGained
        // TODO add your handling code here:
         if ("Nombre".equals(fieldNombre.getText())) {
                fieldNombre.setText("");
                fieldNombre.setForeground(Color.BLACK);  
            }
    }//GEN-LAST:event_fieldNombreFocusGained

    private void fieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreFocusLost
        // TODO add your handling code here:
        if (fieldNombre.getText().isEmpty()) {
            fieldNombre.setText("Nombre");
            fieldNombre.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldNombreFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaAvances dialog = new vistaAvances(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonActualizar;
    public javax.swing.JButton botonBuscar;
    public javax.swing.JButton botonGuardar;
    public javax.swing.JComboBox<String> boxCicloEscolar;
    public javax.swing.JComboBox<String> boxGrado;
    public javax.swing.JComboBox<String> boxTrimestre;
    public javax.swing.JCheckBox checkEtapa1;
    public javax.swing.JCheckBox checkEtapa2;
    public javax.swing.JCheckBox checkEtapa3;
    public javax.swing.JCheckBox checkEtapa4;
    public javax.swing.JCheckBox checkEtapa5;
    public javax.swing.JCheckBox checkEtapa6;
    public javax.swing.JCheckBox checkEtapa7;
    public javax.swing.JTextField fieldApe_materno;
    public javax.swing.JTextField fieldApe_paterno;
    public javax.swing.JTextField fieldNombre;
    public javax.swing.JTextField fieldNumeroControl;
    public javax.swing.ButtonGroup grupoEtapas;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloEtapas;
    public javax.swing.JLabel labelTituloT1;
    private javax.swing.JPanel panelAvances;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane stextEtapa1;
    private javax.swing.JScrollPane stextEtapa2;
    private javax.swing.JScrollPane stextEtapa3;
    private javax.swing.JScrollPane stextEtapa4;
    private javax.swing.JScrollPane stextEtapa5;
    private javax.swing.JScrollPane stextEtapa6;
    private javax.swing.JScrollPane stextEtapa7;
    private javax.swing.JTextPane textEtapa1;
    private javax.swing.JTextPane textEtapa2;
    private javax.swing.JTextPane textEtapa3;
    private javax.swing.JTextPane textEtapa4;
    private javax.swing.JTextPane textEtapa5;
    private javax.swing.JTextPane textEtapa6;
    private javax.swing.JTextPane textEtapa7;
    // End of variables declaration//GEN-END:variables
}
