package vista;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AxiosGaming
 */
public class vistaAltaUsuario extends javax.swing.JDialog {

    public DefaultTableModel modeloTabla;
    
    public JPopupMenu popup = new JPopupMenu();
    public JMenuItem itemSeleccionar = new JMenuItem("Editar datos",new ImageIcon(getClass().getResource("/img/actualizar16x16.png")));
    public JMenuItem itemEliminar = new JMenuItem("Eliminar usuario",new ImageIcon(getClass().getResource("/img/user_remove16x16.png")));
    
    public vistaAltaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();
        scrollUsuarios.getViewport().setBackground(new Color(8,38,67));
        modeloTabla = (DefaultTableModel) tablaUsuarios.getModel() ;
        popupMenuTabla();
    }
    
    private void popupMenuTabla(){
        popup.add(itemSeleccionar);
        popup.add(itemEliminar);
        tablaUsuarios.setComponentPopupMenu(popup);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        fieldIdUsuario = new javax.swing.JTextField();
        panelNombre = new javax.swing.JPanel();
        fieldApe_paterno = new javax.swing.JTextField();
        fieldApe_materno = new javax.swing.JTextField();
        fieldNombre = new javax.swing.JTextField();
        boxFigura_educativa = new javax.swing.JComboBox<>();
        boxSexo = new javax.swing.JComboBox<>();
        txtnombreUser = new javax.swing.JTextField();
        txtcontraseñausuario = new javax.swing.JTextField();
        btnbuscarusuario = new javax.swing.JButton();
        btnagregarusuario = new javax.swing.JButton();
        btnactualizarusuario = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        labelVigencia = new javax.swing.JLabel();
        jDateChooserVigencia = new com.toedter.calendar.JDateChooser();
        panelTabla = new javax.swing.JPanel();
        scrollUsuarios = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(8, 38, 67));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        panelTitulo.setLayout(new java.awt.GridBagLayout());

        labelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Registro de Usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelTitulo.add(labelTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelDatos.setBackground(new java.awt.Color(8, 38, 67));
        panelDatos.setLayout(new java.awt.GridBagLayout());

        fieldIdUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldIdUsuario.setText("Numero de Control");
        fieldIdUsuario.setPreferredSize(new java.awt.Dimension(65, 21));
        fieldIdUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldIdUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldIdUsuarioFocusLost(evt);
            }
        });
        fieldIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(fieldIdUsuario, gridBagConstraints);

        panelNombre.setBackground(new java.awt.Color(0, 51, 102));
        panelNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNombre.setLayout(new java.awt.GridBagLayout());

        fieldApe_paterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldApe_paterno.setText("Apellido Paterno");
        fieldApe_paterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldApe_paternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldApe_paternoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelNombre.add(fieldApe_paterno, gridBagConstraints);

        fieldApe_materno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldApe_materno.setText("Apellido Materno");
        fieldApe_materno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldApe_maternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldApe_maternoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelNombre.add(fieldApe_materno, gridBagConstraints);

        fieldNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldNombre.setText("Nombre");
        fieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNombreFocusLost(evt);
            }
        });
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        panelNombre.add(fieldNombre, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panelDatos.add(panelNombre, gridBagConstraints);

        boxFigura_educativa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxFigura_educativa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Figura Educativa-" }));
        boxFigura_educativa.setMinimumSize(new java.awt.Dimension(65, 21));
        boxFigura_educativa.setPreferredSize(new java.awt.Dimension(6, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        panelDatos.add(boxFigura_educativa, gridBagConstraints);

        boxSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Sexo-", "H", "M" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        panelDatos.add(boxSexo, gridBagConstraints);

        txtnombreUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnombreUser.setText("Usuario");
        txtnombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        panelDatos.add(txtnombreUser, gridBagConstraints);

        txtcontraseñausuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcontraseñausuario.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        panelDatos.add(txtcontraseñausuario, gridBagConstraints);

        btnbuscarusuario.setBackground(new java.awt.Color(8, 38, 67));
        btnbuscarusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnbuscarusuario.setText("Buscar");
        btnbuscarusuario.setBorder(null);
        btnbuscarusuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btnbuscarusuario, gridBagConstraints);

        btnagregarusuario.setBackground(new java.awt.Color(8, 38, 67));
        btnagregarusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnagregarusuario.setText("Guardar");
        btnagregarusuario.setBorder(null);
        btnagregarusuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btnagregarusuario, gridBagConstraints);

        btnactualizarusuario.setBackground(new java.awt.Color(8, 38, 67));
        btnactualizarusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnactualizarusuario.setText("Actualizar");
        btnactualizarusuario.setBorder(null);
        btnactualizarusuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btnactualizarusuario, gridBagConstraints);

        btnLimpiar.setBackground(new java.awt.Color(8, 38, 67));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btnLimpiar, gridBagConstraints);

        labelVigencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVigencia.setForeground(new java.awt.Color(255, 255, 255));
        labelVigencia.setText("Vigencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        panelDatos.add(labelVigencia, gridBagConstraints);

        jDateChooserVigencia.setToolTipText("");
        jDateChooserVigencia.setDateFormatString("yyyy-MM-dd");
        jDateChooserVigencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        panelDatos.add(jDateChooserVigencia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        panelPrincipal.add(panelDatos, gridBagConstraints);

        panelTabla.setBackground(new java.awt.Color(8, 38, 67));
        panelTabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTabla.setLayout(new java.awt.GridLayout(1, 0));

        scrollUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Control", "Figura educativa", "A. paterno", "A. materno", "Nombre", "Sexo", "Usuario", "Contraseña", "Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setGridColor(new java.awt.Color(153, 204, 255));
        scrollUsuarios.setViewportView(tablaUsuarios);

        panelTabla.add(scrollUsuarios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 20);
        panelPrincipal.add(panelTabla, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreUserActionPerformed

    private void fieldIdUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldIdUsuarioFocusGained
        if ("Numero de Control".equals(fieldIdUsuario.getText())) {
            fieldIdUsuario.setText("");
            fieldIdUsuario.setForeground(Color.BLACK);   
        }
    }//GEN-LAST:event_fieldIdUsuarioFocusGained

    private void fieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreFocusGained
        if ("Nombre".equals(fieldNombre.getText())) {
                fieldNombre.setText("");
                fieldNombre.setForeground(Color.BLACK);  
            }
        
    }//GEN-LAST:event_fieldNombreFocusGained

    private void fieldApe_paternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_paternoFocusGained
         if ("Apellido Paterno".equals(fieldApe_paterno.getText())) {
                fieldApe_paterno.setText("");
                fieldApe_paterno.setForeground(Color.BLACK); 
            }
            
    }//GEN-LAST:event_fieldApe_paternoFocusGained

    private void fieldApe_maternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_maternoFocusGained
         if ("Apellido Materno".equals(fieldApe_materno.getText())) {
                fieldApe_materno.setText("");
                fieldApe_materno.setForeground(Color.BLACK);  
            } 
           
    }//GEN-LAST:event_fieldApe_maternoFocusGained

    private void fieldIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdUsuarioActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldIdUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldIdUsuarioFocusLost
        // TODO add your handling code here:
        if (fieldIdUsuario.getText().isEmpty()) {
            fieldIdUsuario.setText("Numero de Control");
            fieldIdUsuario.setForeground(new Color(153, 153,153));
        }
    }//GEN-LAST:event_fieldIdUsuarioFocusLost

    private void fieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreFocusLost
        // TODO add your handling code here:
        if (fieldNombre.getText().isEmpty()) {
            fieldNombre.setText("Nombre");
            fieldNombre.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldNombreFocusLost

    private void fieldApe_paternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_paternoFocusLost
        // TODO add your handling code here:
        if (fieldApe_paterno.getText().isEmpty()) {
            fieldApe_paterno.setText("Apellido Paterno");
            fieldApe_paterno.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldApe_paternoFocusLost

    private void fieldApe_maternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldApe_maternoFocusLost
        // TODO add your handling code here:
        if (fieldApe_materno.getText().isEmpty()) {
            fieldApe_materno.setText("Apellido Materno");
            fieldApe_materno.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldApe_maternoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaAltaUsuario dialog = new vistaAltaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxFigura_educativa;
    public javax.swing.JComboBox<String> boxSexo;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnactualizarusuario;
    public javax.swing.JButton btnagregarusuario;
    public javax.swing.JButton btnbuscarusuario;
    public javax.swing.JTextField fieldApe_materno;
    public javax.swing.JTextField fieldApe_paterno;
    public javax.swing.JTextField fieldIdUsuario;
    public javax.swing.JTextField fieldNombre;
    public com.toedter.calendar.JDateChooser jDateChooserVigencia;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVigencia;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollUsuarios;
    public javax.swing.JTable tablaUsuarios;
    public javax.swing.JTextField txtcontraseñausuario;
    public javax.swing.JTextField txtnombreUser;
    // End of variables declaration//GEN-END:variables
}
