/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AxiosGaming
 */
public class vistaAvancesCapturas extends javax.swing.JFrame {
 
    public DefaultTableModel modeloTabla;
    public JPopupMenu popup = new JPopupMenu();
    public JMenuItem itemEditar = new JMenuItem("Editar datos",new ImageIcon(getClass().getResource("/img/actualizar16x16.png")));
    public JMenuItem itemAvances = new JMenuItem("Registrar Avances",new ImageIcon(getClass().getResource("/img/avances16x16.png")));
    public JMenuItem itemReinscribir = new JMenuItem("Reinscribir",new ImageIcon(getClass().getResource("/img/refres16x16.png")));
    public JMenuItem itemEliminar = new JMenuItem("Eliminar",new ImageIcon(getClass().getResource("/img/eliminarAlumno16x16.png")));
    /**
     * Creates new form interfaz_Principal
     */
    //cambios realizados
  int xx,xy;
    public vistaAvancesCapturas() {
        initComponents();
        modeloTabla = (DefaultTableModel) tablaSituacion.getModel() ;
        popupMenuTabla();
        personalizarComponentes();
       
    }
    
    private void popupMenuTabla(){
       
//        popup.add(itemEditar);
//        popup.add(itemAvances);
//        popup.add(itemReinscribir);
//        popup.add(itemEliminar);
        tablaSituacion.setComponentPopupMenu(popup);
    }
    
    private void personalizarComponentes(){
        scrollTablaPrincipal.getViewport().setBackground(new Color(8,38,67));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        boxCicloEscolar = new javax.swing.JComboBox<>();
        boxRegion = new javax.swing.JComboBox<>();
        boxGrado = new javax.swing.JComboBox<>();
        boxSituacion = new javax.swing.JComboBox<>();
        panelBotones = new javax.swing.JPanel();
        panelTabla = new javax.swing.JPanel();
        scrollTablaPrincipal = new javax.swing.JScrollPane();
        tablaSituacion = new javax.swing.JTable();

        setExtendedState(MAXIMIZED_BOTH);
        setName("Avances en las capturas"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(8, 38, 67));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        panelTitulo.setLayout(new java.awt.GridBagLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Avances de capturas");
        panelTitulo.add(labelTitulo, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelCampos.setBackground(new java.awt.Color(8, 38, 67));
        panelCampos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelCampos.setLayout(new java.awt.GridBagLayout());

        boxCicloEscolar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxCicloEscolar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione Ciclo Escolar -" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCampos.add(boxCicloEscolar, gridBagConstraints);

        boxRegion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione Region -" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCampos.add(boxRegion, gridBagConstraints);

        boxGrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione Grado -" }));
        boxGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGradoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCampos.add(boxGrado, gridBagConstraints);

        boxSituacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxSituacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Situacion actual/final -" }));
        boxSituacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSituacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelCampos.add(boxSituacion, gridBagConstraints);

        panelBotones.setBackground(new java.awt.Color(8, 38, 67));
        panelBotones.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panelCampos.add(panelBotones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        panelPrincipal.add(panelCampos, gridBagConstraints);

        panelTabla.setBackground(new java.awt.Color(8, 38, 67));
        panelTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTabla.setLayout(new java.awt.GridLayout(1, 0));

        scrollTablaPrincipal.setBackground(new java.awt.Color(0, 51, 102));
        scrollTablaPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        scrollTablaPrincipal.setOpaque(false);

        tablaSituacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaSituacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ciclo escolar", "Region", "No. Control", "Grado", "Apellido paterno", "Apellido materno", "Nombre", "T1", "T2", "T3", "Situacion Actual/Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSituacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaSituacion.setGridColor(new java.awt.Color(153, 204, 255));
        tablaSituacion.setSelectionBackground(new java.awt.Color(204, 204, 255));
        scrollTablaPrincipal.setViewportView(tablaSituacion);
        tablaSituacion.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablaSituacion.getColumnModel().getColumnCount() > 0) {
            tablaSituacion.getColumnModel().getColumn(0).setMinWidth(80);
            tablaSituacion.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablaSituacion.getColumnModel().getColumn(0).setMaxWidth(120);
            tablaSituacion.getColumnModel().getColumn(1).setMinWidth(80);
            tablaSituacion.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablaSituacion.getColumnModel().getColumn(1).setMaxWidth(120);
            tablaSituacion.getColumnModel().getColumn(2).setMinWidth(80);
            tablaSituacion.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaSituacion.getColumnModel().getColumn(2).setMaxWidth(120);
            tablaSituacion.getColumnModel().getColumn(3).setMinWidth(50);
            tablaSituacion.getColumnModel().getColumn(3).setPreferredWidth(70);
            tablaSituacion.getColumnModel().getColumn(3).setMaxWidth(80);
            tablaSituacion.getColumnModel().getColumn(4).setMinWidth(120);
            tablaSituacion.getColumnModel().getColumn(4).setPreferredWidth(150);
            tablaSituacion.getColumnModel().getColumn(4).setMaxWidth(200);
            tablaSituacion.getColumnModel().getColumn(5).setMinWidth(120);
            tablaSituacion.getColumnModel().getColumn(5).setPreferredWidth(150);
            tablaSituacion.getColumnModel().getColumn(5).setMaxWidth(200);
            tablaSituacion.getColumnModel().getColumn(6).setMinWidth(120);
            tablaSituacion.getColumnModel().getColumn(6).setPreferredWidth(150);
            tablaSituacion.getColumnModel().getColumn(6).setMaxWidth(200);
            tablaSituacion.getColumnModel().getColumn(7).setMinWidth(40);
            tablaSituacion.getColumnModel().getColumn(7).setPreferredWidth(50);
            tablaSituacion.getColumnModel().getColumn(7).setMaxWidth(70);
            tablaSituacion.getColumnModel().getColumn(8).setMinWidth(40);
            tablaSituacion.getColumnModel().getColumn(8).setPreferredWidth(50);
            tablaSituacion.getColumnModel().getColumn(8).setMaxWidth(70);
            tablaSituacion.getColumnModel().getColumn(9).setMinWidth(40);
            tablaSituacion.getColumnModel().getColumn(9).setPreferredWidth(50);
            tablaSituacion.getColumnModel().getColumn(9).setMaxWidth(70);
            tablaSituacion.getColumnModel().getColumn(10).setMinWidth(100);
            tablaSituacion.getColumnModel().getColumn(10).setPreferredWidth(120);
            tablaSituacion.getColumnModel().getColumn(10).setMaxWidth(200);
        }

        panelTabla.add(scrollTablaPrincipal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        panelPrincipal.add(panelTabla, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGradoActionPerformed

    private void boxSituacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSituacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSituacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAvancesCapturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAvancesCapturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAvancesCapturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAvancesCapturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAvancesCapturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxCicloEscolar;
    public javax.swing.JComboBox<String> boxGrado;
    public javax.swing.JComboBox<String> boxRegion;
    public javax.swing.JComboBox<String> boxSituacion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollTablaPrincipal;
    public javax.swing.JTable tablaSituacion;
    // End of variables declaration//GEN-END:variables
}
