/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JTextField;

/**
 *
 * @author AxiosGaming
 */
public class vistaAltaUsuario extends javax.swing.JDialog {

    /**
     * Creates new form vistaAltaUsuario
     */
    public vistaAltaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();
        JTextField [] tfs ={txtnocontrolusuario,txtnombreusuario,txtapellidopaterno,txtapellidomaternousuario,txtnombredeusuario,txtcontraseñausuario};
        HintText(tfs);
        
    }
    
    private void HintText(JTextField [] tfs)
    {
        for(JTextField jtf: tfs){
            
            jtf.addFocusListener(new FocusListener(){
                @Override
                public void focusGained(FocusEvent fe) 
                {
                    if(jtf.getText().equals("Numero de Control*")){
                        jtf.setText("");
                    }
                    if(jtf.getText().equals("Nombre*")){
                        jtf.setText("");
                        
                    }
                    if(jtf.getText().equals("Apellido Paterno*")){
                        jtf.setText("");
                        
                    }if(jtf.getText().equals("Apellido Materno*")){
                        jtf.setText("");
                        
                    }if(jtf.getText().equals("Usuario*")){
                        jtf.setText("");
                        
                    }if(jtf.getText().equals("Contraseña*")){
                        jtf.setText("");
                        
                    }
                }

                @Override
                public void focusLost(FocusEvent fe) 
                {
                if(jtf.equals(txtnocontrolusuario) && jtf.getText().equals("")){
                    jtf.setText(("Numero de Control*"));
                } if(jtf.equals(txtnombreusuario) && jtf.getText().equals("")){
                    jtf.setText(("Nombre*"));
                }  if(jtf.equals(txtapellidopaterno) && jtf.getText().equals("")){
                    jtf.setText(("Apellido Paterno*"));
                } if(jtf.equals(txtapellidomaternousuario) && jtf.getText().equals("")){
                    jtf.setText(("Apellido Materno*"));
                }   if(jtf.equals(txtnombredeusuario) && jtf.getText().equals("")){
                    jtf.setText(("Usuario*"));
                }    if(jtf.equals(txtcontraseñausuario) && jtf.getText().equals("")){
                    jtf.setText(("Contraseña*"));
                }     
                }
                
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        txtnocontrolusuario = new javax.swing.JTextField();
        txtnombreusuario = new javax.swing.JTextField();
        txtapellidopaterno = new javax.swing.JTextField();
        txtapellidomaternousuario = new javax.swing.JTextField();
        cbxfiguraeducativa = new javax.swing.JComboBox<>();
        cbxsexo = new javax.swing.JComboBox<>();
        txtnombredeusuario = new javax.swing.JTextField();
        txtcontraseñausuario = new javax.swing.JTextField();
        btnbuscarusuario = new javax.swing.JButton();
        btnagregarusuario = new javax.swing.JButton();
        btnactualizarusuario = new javax.swing.JButton();
        btneliminarusuario = new javax.swing.JButton();
        labelVigencia = new javax.swing.JLabel();
        jDateChooserVigencia = new com.toedter.calendar.JDateChooser();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        panelPrincipal.setBackground(new java.awt.Color(8, 38, 67));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        panelTitulo.setLayout(new java.awt.GridBagLayout());

        labelTitulo.setBackground(new java.awt.Color(8, 38, 67));
        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Registro de Usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelTitulo.add(labelTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelPrincipal.add(panelTitulo, gridBagConstraints);

        panelDatos.setBackground(new java.awt.Color(8, 38, 67));
        panelDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDatos.setLayout(new java.awt.GridBagLayout());

        txtnocontrolusuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnocontrolusuario.setText("Numero de Control*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(txtnocontrolusuario, gridBagConstraints);

        txtnombreusuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnombreusuario.setText("Nombre*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(txtnombreusuario, gridBagConstraints);

        txtapellidopaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtapellidopaterno.setText("Apellido Paterno*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(txtapellidopaterno, gridBagConstraints);

        txtapellidomaternousuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtapellidomaternousuario.setText("Apellido Materno*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(txtapellidomaternousuario, gridBagConstraints);

        cbxfiguraeducativa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxfiguraeducativa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Figura Educativa-" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panelDatos.add(cbxfiguraeducativa, gridBagConstraints);

        cbxsexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-sexo-" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panelDatos.add(cbxsexo, gridBagConstraints);

        txtnombredeusuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnombredeusuario.setText("Usuario*");
        txtnombredeusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombredeusuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panelDatos.add(txtnombredeusuario, gridBagConstraints);

        txtcontraseñausuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcontraseñausuario.setText("Contraseña*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        panelDatos.add(txtcontraseñausuario, gridBagConstraints);

        btnbuscarusuario.setBackground(new java.awt.Color(8, 38, 67));
        btnbuscarusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnbuscarusuario.setText("Buscar");
        btnbuscarusuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btnbuscarusuario, gridBagConstraints);

        btnagregarusuario.setBackground(new java.awt.Color(8, 38, 67));
        btnagregarusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnagregarusuario.setText("Guardar");
        btnagregarusuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btnagregarusuario, gridBagConstraints);

        btnactualizarusuario.setBackground(new java.awt.Color(8, 38, 67));
        btnactualizarusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnactualizarusuario.setText("Actualizar");
        btnactualizarusuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btnactualizarusuario, gridBagConstraints);

        btneliminarusuario.setText("Eliminar");
        btneliminarusuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelDatos.add(btneliminarusuario, gridBagConstraints);

        labelVigencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVigencia.setForeground(new java.awt.Color(255, 255, 255));
        labelVigencia.setText("Vigencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        panelDatos.add(labelVigencia, gridBagConstraints);

        jDateChooserVigencia.setToolTipText("");
        jDateChooserVigencia.setDateFormatString("yyyy-MM-dd");
        jDateChooserVigencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        panelDatos.add(jDateChooserVigencia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        panelPrincipal.add(panelDatos, gridBagConstraints);

        panelTabla.setBackground(new java.awt.Color(8, 38, 67));
        panelTabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTabla.setLayout(new java.awt.GridLayout(1, 0));

        tablaUsuarios.setBackground(new java.awt.Color(8, 38, 67));
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Control", "Figura educativa", "A. paterno", "A. materno", "Nombre", "Usuario", "Contraseña", "Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        panelTabla.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 20);
        panelPrincipal.add(panelTabla, gridBagConstraints);

        getContentPane().add(panelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombredeusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombredeusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombredeusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaAltaUsuario dialog = new vistaAltaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizarusuario;
    private javax.swing.JButton btnagregarusuario;
    private javax.swing.JButton btnbuscarusuario;
    private javax.swing.JButton btneliminarusuario;
    private javax.swing.JComboBox<String> cbxfiguraeducativa;
    private javax.swing.JComboBox<String> cbxsexo;
    private com.toedter.calendar.JDateChooser jDateChooserVigencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVigencia;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtapellidomaternousuario;
    private javax.swing.JTextField txtapellidopaterno;
    private javax.swing.JTextField txtcontraseñausuario;
    private javax.swing.JTextField txtnocontrolusuario;
    private javax.swing.JTextField txtnombredeusuario;
    private javax.swing.JTextField txtnombreusuario;
    // End of variables declaration//GEN-END:variables
}
